const {chromium}=require('@playwright/test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:900}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:5173/?v=3');
  await page.locator('.topic-section').last().waitFor();
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('.topic-section').count(),9);
  assert.equal(await page.locator('.rule-row').count(),78);
  assert.equal(await page.locator('.hero,.brand,.topic-card,dialog').count(),0);
  const initiallyVisible=await page.locator('.rule-row').evaluateAll(rows=>rows.filter(row=>{const r=row.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}).length);
  assert.ok(initiallyVisible>=7,`Only ${initiallyVisible} rules visible on entry`);
  fs.mkdirSync('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/reference-desktop.png'});
  await page.locator('#search').fill('Vieta');
  assert.equal(await page.locator('.rule-row').count(),1);
  assert.ok(await page.locator('.rule-formula .katex').count());
  assert.match(await page.locator('.rule-name').textContent(),/Vieta/);
  await page.screenshot({path:'artifacts/reference-search.png'});
  await page.locator('#clear-search').click();
  await page.locator('[data-filter="7"]').click();
  assert.equal(await page.locator('.topic-section').count(),5);
  await page.locator('#topic-nav a[href="#topic-9"]').click();
  assert.equal(await page.locator('.topic-section').count(),9);
  assert.equal(new URL(page.url()).hash,'#topic-9');
  const bounds=await page.locator('#title-9').boundingBox();assert.ok(bounds.y>60&&bounds.y<180);
  await page.locator('[data-save="9"]').click();
  await page.locator('#saved-filter').click();
  assert.equal(await page.locator('.topic-section').count(),1);
  await page.reload();
  assert.equal(await page.locator('#saved-count').textContent(),'1');
  await page.locator('#search').fill('unfindable');
  assert.equal(await page.locator('.rule-row').count(),0);
  await page.locator('[data-reset]').click();
  assert.equal(await page.locator('.topic-section').count(),9);
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:'artifacts/reference-mobile.png'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Page overflows');
  await page.locator('#topic-select').selectOption('5');
  assert.equal(new URL(page.url()).hash,'#topic-5');
  assert.ok(await page.locator('#topic-5 .rule-formula .katex').count());
  await page.screenshot({path:'artifacts/reference-fractions-mobile.png'});
  const overflow=await page.locator('.rule-formula').evaluateAll(nodes=>nodes.filter(n=>n.scrollWidth>n.clientWidth+2).map(n=>n.textContent));
  assert.deepEqual(overflow,[],'Mobile formulas should fit');
  assert.deepEqual(errors,[]);
  console.log(`Passed: 78 rules visible without opening lessons; ${initiallyVisible} rules on first screen; exact rule search, navigation, filters, bookmarks, mobile formulas.`);
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1});
