const $=selector=>document.querySelector(selector);
let saved=[];
try{const stored=JSON.parse(localStorage.getItem('mathe-atlas')||'{}');if(Array.isArray(stored.saved))saved=[...new Set(stored.saved.filter(id=>topics.some(t=>t.id===id)))];}catch{}
let filter='all',savedOnly=false,query='';
const plain=source=>source.replace(/\\(?:dfrac|frac|sqrt|left|right|quad|begin|end|text|mathbb|cdot|ne|ge|le|pm|mid|underbrace|overline|setminus|subset|in|ldots|Rightarrow|longrightarrow|Delta)\b/g,' ').replace(/[${}\\_^]/g,' ').replace(/<[^>]*>/g,' ').toLocaleLowerCase('de');
function matches(text){return query.toLocaleLowerCase('de').split(/\s+/).filter(Boolean).every(word=>plain(text).includes(word));}
function matchingTopics(){return topics.filter(t=>(filter==='all'||String(t.grade)===filter)&&(!savedOnly||saved.includes(t.id))).map(t=>({topic:t,rows:t.rows.map((row,index)=>({row,index})).filter(({row,index})=>!query||matches(t.title)||matches(row.join(' ')+' '+t.rawRows[index].join(' ')))})).filter(t=>t.rows.length);}
function persist(){try{const old=JSON.parse(localStorage.getItem('mathe-atlas')||'{}');localStorage.setItem('mathe-atlas',JSON.stringify({...old,saved}));}catch{}}
function graph(type){const root=type==='root';const path=root?'M90 200 '+Array.from({length:101},(_,i)=>{const x=i*9/100;return `L${90+x*25} ${200-Math.sqrt(x)*45}`}).join(' '):'M40 225 L250 15';return `<details class="graph-details"><summary>Funktionsgraph anzeigen</summary><svg class="graph" viewBox="0 0 360 250" role="img" aria-label="${root?'Graph der Quadratwurzelfunktion':'Gerade mit Steigung eins und Achsenabschnitt eins'}"><path d="M40 200H340 M90 230V15" stroke="#af9270"/><path d="${path}" fill="none" stroke="#8b4b42" stroke-width="2.5"/><g fill="#755b44" font-size="10"><text x="340" y="216">x</text><text x="75" y="18">y</text><text x="77" y="214">0</text>${root?'<text x="112" y="214">1</text><text x="188" y="214">4</text><text x="313" y="214">9</text><text x="76" y="159">1</text><text x="76" y="114">2</text><text x="76" y="69">3</text>':'<text x="113" y="214">1</text><text x="76" y="179">1</text><text x="76" y="154">2</text>'}</g></svg><div class="graph-label">${math(root?String.raw`y=\sqrt x`:'y=x+1')}</div></details>`;}
function render(){
 const results=matchingTopics();const count=results.reduce((sum,t)=>sum+t.rows.length,0);
 $('#rules').innerHTML=results.length?results.map(({topic:t,rows})=>`<section class="topic-section" id="topic-${t.id}" aria-labelledby="title-${t.id}"><div class="topic-heading"><span class="topic-number">${String(t.id).padStart(2,'0')}</span><h2 id="title-${t.id}">${t.title}</h2><span class="topic-grade">Klasse ${t.grade}</span><button class="save-topic" data-save="${t.id}" aria-label="${saved.includes(t.id)?'Aus Merkliste entfernen':'Thema merken'}: ${t.title}" aria-pressed="${saved.includes(t.id)}">${saved.includes(t.id)?'♥':'♡'}</button></div><div class="rule-table" role="table" aria-label="${t.title}"><div class="table-head" role="row"><div role="columnheader">Regel</div><div role="columnheader">Formel / Beispiel</div><div role="columnheader">Bedingung / Merkhilfe</div></div>${rows.map(({row,index})=>`<div class="rule-row" role="row" id="rule-${t.id}-${index}"><div class="rule-name" role="rowheader">${rich(row[0])}</div><div class="rule-formula" role="cell" tabindex="0">${rich(row[1])}</div><div class="rule-note" role="cell">${rich(row[2])}</div></div>`).join('')}</div>${query?'':`<div class="topic-support"><div class="warning"><div class="support-label">Achtung</div>${rich(t.warning)}</div><div class="example"><div class="support-label">Beispiel mit Lösungsweg</div><div class="example-question">${rich(t.example[0])}</div><div class="example-solution">${rich(t.example[1])}</div></div></div>${t.graph?graph(t.graph):''}<div class="related">Verknüpft mit: ${t.related.map(id=>`<a href="#topic-${id}">${topics[id-1].title}</a>`).join(' · ')}</div>`}</section>`).join(''):`<div class="empty"><p>${savedOnly&&!saved.length?'Deine Merkliste ist leer. Über das Herz neben einer Themenüberschrift kannst du ein Thema merken.':'Keine passenden Regeln. Versuche einen anderen Begriff oder setze die Filter zurück.'}</p><button data-reset>Alle Regeln anzeigen</button></div>`;
 $('#result-count').textContent=`${count} ${count===1?'Regel':'Regeln'}`;$('#saved-count').textContent=saved.length;
 document.querySelectorAll('[data-filter]').forEach(button=>button.setAttribute('aria-pressed',button.dataset.filter===filter));$('#saved-filter').setAttribute('aria-pressed',savedOnly);
 $('#search-status').hidden=!query;
 if(query)$('#search-status span').textContent=`${count} ${count===1?'Regel':'Regeln'} für „${query}“`;
 observeSections();
}
let observer;
function markActive(id){document.querySelectorAll('#topic-nav a').forEach(a=>{const active=a.hash===`#topic-${id}`;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});$('#topic-select').value=String(id);}
function observeSections(){if(observer)observer.disconnect();const sections=[...document.querySelectorAll('.topic-section')];if(sections.length)markActive(sections[0].id.split('-')[1]);if(!('IntersectionObserver' in window))return;observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);if(visible.length)markActive(visible[0].target.id.split('-')[1]);},{rootMargin:'-90px 0px -65% 0px',threshold:0});sections.forEach(s=>observer.observe(s));}
function goToTopic(id){if(!topics.some(t=>t.id===id))return;filter='all';savedOnly=false;query='';$('#search').value='';render();const section=$(`#topic-${id}`);section.scrollIntoView({behavior:'auto',block:'start'});history.replaceState(null,'',`#topic-${id}`);markActive(id);const heading=$(`#title-${id}`);heading.tabIndex=-1;heading.focus({preventScroll:true});}
function reset(){filter='all';savedOnly=false;query='';$('#search').value='';render();}
$('#topic-nav').innerHTML=[7,8].map(grade=>`<section class="nav-grade" aria-labelledby="nav-grade-${grade}"><h2 id="nav-grade-${grade}">Klasse ${grade}</h2>${topics.filter(t=>t.grade===grade).map(t=>`<a href="#topic-${t.id}"><span>${String(t.id).padStart(2,'0')}</span><span>${t.title}</span></a>`).join('')}</section>`).join('');
$('#topic-select').innerHTML='<option value="">Thema auswählen</option>'+[7,8].map(grade=>`<optgroup label="Klasse ${grade}">${topics.filter(t=>t.grade===grade).map(t=>`<option value="${t.id}">${t.title}</option>`).join('')}</optgroup>`).join('');
$('#topic-select').addEventListener('change',e=>goToTopic(+e.target.value));
document.addEventListener('click',e=>{const anchor=e.target.closest('a[href^="#topic-"]');if(anchor){e.preventDefault();goToTopic(+anchor.hash.replace('#topic-',''));return;}const b=e.target.closest('button');if(!b)return;if(b.dataset.filter){filter=b.dataset.filter;render();}if(b.id==='saved-filter'){savedOnly=!savedOnly;render();}if(b.dataset.save){const id=+b.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];persist();if(savedOnly)render();else{b.setAttribute('aria-pressed',saved.includes(id));b.textContent=saved.includes(id)?'♥':'♡';b.setAttribute('aria-label',`${saved.includes(id)?'Aus Merkliste entfernen':'Thema merken'}: ${topics[id-1].title}`);$('#saved-count').textContent=saved.length;}}if(b.hasAttribute('data-reset'))reset();});
$('#search').addEventListener('input',e=>{query=e.target.value.trim();render();});
$('#clear-search').addEventListener('click',()=>{query='';$('#search').value='';render();$('#search').focus();});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus();}});
render();
if(/^#topic-\d+$/.test(location.hash))requestAnimationFrame(()=>goToTopic(+location.hash.replace('#topic-','')));
